# Generated by Django 3.0.8 on 2020-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('open_time_week', models.CharField(max_length=10, verbose_name='opening time on week days')),
                ('am_pm_ow', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=10, verbose_name='am/pm')),
                ('close_time_week', models.CharField(max_length=10, verbose_name='Closing time on week days')),
                ('am_pm_cw', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=10, verbose_name='am/pm')),
                ('open_time_end', models.CharField(max_length=10, verbose_name='opening time on weekend days')),
                ('am_pm_oe', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=10, verbose_name='am/pm')),
                ('close_time_end', models.CharField(max_length=10, verbose_name='Closing time on weekend days')),
                ('am_pm_ce', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=10, verbose_name='am/pm')),
            ],
        ),
    ]
